[build]
  base = "./"
  publish = "./dist/"
  command = "node builder/init.js --local && npx parcel build src/index.html"

[build.environment]
  NAME = "Guru Ji"
  PIC = "sample-pic.jpg"
  NICKNAME = "Guruji"
  HBD_MSG = "आदरणीय गुरुवर्य,जन्मदिनस्य हार्दिकाः शुभकामनाः।"
  OPEN_DATE = "2026-06-12"

[template.environment]
  NAME = "Guru Ji"
  PIC = "sample-pic.jpg"
