[build]
  base = "./"
  publish = "./dist/"
  command = "node builder/init.js --local && npx parcel build src/index.html"

[build.environment]
  NAME = "Guru Ji"
  PIC = "sample-pic.jpeg"
  NICKNAME = "Guruji"
  HBD_MSG = "May your birthday be filled with joy and happiness"
  OPEN_DATE = "2026-06-10"

[template.environment]
  NAME = "Guru Ji"
  PIC = "sample-pic.jpeg"
